Repository yash244466666/Catalog-of-My-things, pull requests merged in 2023-04, with the labels that each got.

#31 Create Label class
  label.rb
Labels: backend

#32 Create Genre class
  genre.rb
Labels: enhancement, backend, setter-methods, association, refactor

#35 Preserve labels and books data
  book.rb
  data/books.json
  data/labels.json
  label.rb
Labels: enhancement, backend, refactor, preserve_data

#36 Preserve music album and genre genre data
  data/genres.json
  data/music_albums.json
  genre.rb
  music_album.rb
Labels: enhancement, backend, association, refactor, preserve_data

#38 Unit tests for Book and Label classes
  label.rb
  spec/book_spec.rb
  spec/label_spec.rb
Labels: enhancement, backend, refactor, unit_tests

#41 Create schema for Music albums and Genres tables
  database/schema.sql
Labels: enhancement, backend, association, refactor

#47 Catalog-of-My-Things
  .github/workflows/linters.yml
  .github/workflows/tests.yml
  .rubocop.yml
  Gemfile
  Gemfile.lock
  LICENSE
  README.md
  app.rb
  author.rb
  book.rb
  data/authors.json
  data/books.json
  data/game.json
  data/genres.json
  data/labels.json
  data/music_albums.json
  database/data.sql
  database/querie.sql
  database/schema.sql
  game.rb
  genre.rb
  item.rb
  label.rb
  main.rb
  music_album.rb
  spec/author_spec.rb
  spec/book_spec.rb
  spec/game_spec.rb
  spec/genre_spec.rb
  spec/label_spec.rb
  spec/musicalbum_spec.rb
Labels: backend, setter-methods, association, preserve_data, unit_tests
